/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.BorderLayout;

/**
 *
 * @author nujif
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WorkBench = new javax.swing.JPanel();
        Pantalla = new javax.swing.JPanel();
        TitleLanding = new javax.swing.JLabel();
        InfoText_1 = new javax.swing.JLabel();
        InfoText_2 = new javax.swing.JLabel();
        LandingPicture = new javax.swing.JLabel();
        HeadTop = new javax.swing.JLabel();
        ButtonInicio = new javax.swing.JButton();
        ButtonEventos = new javax.swing.JButton();
        FooterPicture = new javax.swing.JLabel();
        FooterText_1 = new javax.swing.JLabel();
        Line = new javax.swing.JSeparator();
        FooterText_2 = new javax.swing.JLabel();
        ButtonCrud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WorkBench.setBackground(new java.awt.Color(255, 255, 255));
        WorkBench.setPreferredSize(new java.awt.Dimension(1286, 1026));

        Pantalla.setBackground(new java.awt.Color(51, 51, 51));
        Pantalla.setPreferredSize(new java.awt.Dimension(1280, 664));

        TitleLanding.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 1, 70)); // NOI18N
        TitleLanding.setForeground(new java.awt.Color(194, 204, 9));
        TitleLanding.setText("E-BANK UTS");

        InfoText_1.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 0, 15)); // NOI18N
        InfoText_1.setForeground(new java.awt.Color(255, 255, 255));
        InfoText_1.setText("En EBank UTS, estamos transformando la manera en que interactúas con tus finanzas. Nuestra app está diseñada   ");

        InfoText_2.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 0, 15)); // NOI18N
        InfoText_2.setForeground(new java.awt.Color(255, 255, 255));
        InfoText_2.setText("para ofrecerte la máxima comodidad, seguridad y control total sobre tu dinero, estés donde estés.");

        LandingPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LandingImage.png"))); // NOI18N

        javax.swing.GroupLayout PantallaLayout = new javax.swing.GroupLayout(Pantalla);
        Pantalla.setLayout(PantallaLayout);
        PantallaLayout.setHorizontalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaLayout.createSequentialGroup()
                        .addComponent(TitleLanding)
                        .addGap(306, 306, 306))
                    .addComponent(InfoText_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaLayout.createSequentialGroup()
                        .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InfoText_2)
                            .addGroup(PantallaLayout.createSequentialGroup()
                                .addComponent(LandingPicture)
                                .addGap(233, 233, 233)))
                        .addGap(80, 80, 80)))
                .addGap(110, 110, 110))
        );
        PantallaLayout.setVerticalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(TitleLanding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoText_1)
                .addGap(0, 0, 0)
                .addComponent(InfoText_2)
                .addGap(18, 18, 18)
                .addComponent(LandingPicture)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        HeadTop.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 1, 36)); // NOI18N
        HeadTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HeadImage.jpg"))); // NOI18N
        HeadTop.setText("E-BANK UTS");

        ButtonInicio.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 1, 20)); // NOI18N
        ButtonInicio.setText("INICIO");
        ButtonInicio.setBorderPainted(false);
        ButtonInicio.setContentAreaFilled(false);
        ButtonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInicioActionPerformed(evt);
            }
        });

        ButtonEventos.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 1, 20)); // NOI18N
        ButtonEventos.setText("EVENTOS");
        ButtonEventos.setBorderPainted(false);
        ButtonEventos.setContentAreaFilled(false);
        ButtonEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEventosActionPerformed(evt);
            }
        });

        FooterPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FooterImage.png"))); // NOI18N

        FooterText_1.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 0, 14)); // NOI18N
        FooterText_1.setText("UNIDADES TECNOLOGICAS DE SANTANDER");

        Line.setForeground(new java.awt.Color(0, 0, 0));

        FooterText_2.setText("Copyright © 2024 Made whit <3 In Colombia");

        ButtonCrud.setFont(new java.awt.Font("Jumper PERSONAL USE ONLY Bold", 1, 20)); // NOI18N
        ButtonCrud.setText("CRUD");
        ButtonCrud.setBorder(null);
        ButtonCrud.setBorderPainted(false);
        ButtonCrud.setContentAreaFilled(false);
        ButtonCrud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WorkBenchLayout = new javax.swing.GroupLayout(WorkBench);
        WorkBench.setLayout(WorkBenchLayout);
        WorkBenchLayout.setHorizontalGroup(
            WorkBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 1286, Short.MAX_VALUE)
            .addGroup(WorkBenchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WorkBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WorkBenchLayout.createSequentialGroup()
                        .addComponent(HeadTop)
                        .addGap(243, 243, 243)
                        .addComponent(ButtonInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(ButtonEventos)
                        .addGap(106, 106, 106)
                        .addComponent(ButtonCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkBenchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(WorkBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkBenchLayout.createSequentialGroup()
                                .addComponent(FooterPicture)
                                .addGap(586, 586, 586))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkBenchLayout.createSequentialGroup()
                                .addComponent(FooterText_1)
                                .addGap(475, 475, 475))))))
            .addComponent(Line)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WorkBenchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FooterText_2)
                .addGap(507, 507, 507))
        );
        WorkBenchLayout.setVerticalGroup(
            WorkBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkBenchLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(WorkBenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HeadTop)
                    .addComponent(ButtonInicio)
                    .addComponent(ButtonEventos)
                    .addComponent(ButtonCrud))
                .addGap(18, 18, 18)
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FooterPicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FooterText_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Line, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FooterText_2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(WorkBench, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(WorkBench, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInicioActionPerformed
        
    }//GEN-LAST:event_ButtonInicioActionPerformed

    private void ButtonEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEventosActionPerformed
        CrudEventos e1 = new CrudEventos();
        e1.setSize(1280,664);
        e1.setLocation(0,0);

        Pantalla.removeAll();
        Pantalla.add(e1,BorderLayout.CENTER);
        Pantalla.revalidate();
        Pantalla.repaint();
    }//GEN-LAST:event_ButtonEventosActionPerformed

    private void ButtonCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrudActionPerformed
        CRUD c1 = new CRUD();
        c1.setSize(1280,664);
        c1.setLocation(0,0);

        Pantalla.removeAll();
        Pantalla.add(c1,BorderLayout.CENTER);
        Pantalla.revalidate();
        Pantalla.repaint();
    }//GEN-LAST:event_ButtonCrudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCrud;
    private javax.swing.JButton ButtonEventos;
    private javax.swing.JButton ButtonInicio;
    private javax.swing.JLabel FooterPicture;
    private javax.swing.JLabel FooterText_1;
    private javax.swing.JLabel FooterText_2;
    private javax.swing.JLabel HeadTop;
    private javax.swing.JLabel InfoText_1;
    private javax.swing.JLabel InfoText_2;
    private javax.swing.JLabel LandingPicture;
    private javax.swing.JSeparator Line;
    private javax.swing.JPanel Pantalla;
    private javax.swing.JLabel TitleLanding;
    private javax.swing.JPanel WorkBench;
    // End of variables declaration//GEN-END:variables
}
